### ISSUE TITLE
Unable to setup MiCoP

### ISSUE THREAD

**Issue by thierroll** [smangul1/MiCoP#3]
Hi,
I am unable to install MiCoP as I get the following error message:
" awk: can't open file ./cookie". This seems to link to a file on a Google Drive according to the script. Has the file maybe moved or is differently named?

Many thanks,
Thierry

**Comment by nlapier2** [comment]
Hi Thierry, sorry for the delay. I haven't been able to replicate this error. Can you tell me exactly what lines you ran to get this error? Did you download the repository and then immediately run the setup, or did you try running the setup or something else beforehand?

**Comment by thierroll** [comment]
Hi Nathan,

 

Thanks for getting back to me. In the meantime I figured out the problem. Within the institution network I am not allowed to access google drive. 

I have used a workaround and copied the repository to the computer (in /MiCoP/data ), so that all the files (fungi-refseq.fna.* and viral-refseqg.fna.*) are there.

 

However if I run the script run-bwa.py script as follows

 

“python run-bwa.py reads.fq --fungi”

 

I get the error message: “Eror: must specify either –virus or –fungi”, which I did.

 

Could you help me out with this?

 

Many thanks,

Thierry Rolling

**Comment by nlapier2** [comment]
Hi Thierry,

I haven't been able to replicate this error. Another issue mentioned that there are problems with certain versions of python. Can you report your version via "python --version"? Also, is that the exact line you ran? If not can you paste it here please? (You can redact the reads file name if you want)

Best,
Nathan

**Comment by thierroll** [comment]
Hi Nathan,

 

My Python version is:  3.7.3

 

 

The lines I ran are: 

 

cd micop

python run-bwa.py 34D_clean.fastq --fungi

 

[I copied the fastq file into the micop working directory for this one]

 

I get the following error message:

 

File “run-bwa.py”, line 23

   Print ‘Error: must specify either --virus or --fungi.’

SyntaxError: Missing parentheses in call to ‘print’. Did you mean print(‘Error: must specify either --virus or --fungi.’)?

 

I wonder whether this is due to the fact that I manually copied the indices into the data folder?

What files should be in the data folder [filenames]?

 

Many thanks

 

Thierry

**Comment by nlapier2** [comment]
The error above is due to python 3 having different print syntax. Try running it with python 2 and see if it works. I will work on making this compatible with more versions of python soon. For now, the safest bet is python 2.7.

**Comment by thierroll** [comment]
Hello Nathan,

 

I am truly sorry, but I still cannot get the code to work even after installing python 2.7

 

Please find the error code below:

 

(base) MSKI2219:micop rollingt$ python run-bwa.py 34D_clean.fastq --fungi

Traceback (most recent call last):

  File "run-bwa.py", line 41, in <module>

    main()

  File "run-bwa.py", line 37, in main

    subprocess.call(shlex.split(cmd), stdout=outfile)

  File "/Users/rollingt/miniconda3/lib/python2.7/subprocess.py", line 172, in call

    return Popen(*popenargs, **kwargs).wait()

  File "/Users/rollingt/miniconda3/lib/python2.7/subprocess.py", line 394, in __init__

    errread, errwrite)

  File "/Users/rollingt/miniconda3/lib/python2.7/subprocess.py", line 1047, in _execute_child

    raise child_exception

OSError: [Errno 8] Exec format error

 

 

Many thanks again,
Thierry

**Comment by bautist2** [comment]
Hi there,

I'm having the exact same problem. I also have python 2.7.

Traceback (most recent call last):
  File "run-bwa.py", line 41, in <module>
    main()
  File "run-bwa.py", line 37, in main
    subprocess.call(shlex.split(cmd), stdout=outfile)
  File "/Users/mbautista/miniconda2/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/mbautista/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Users/mbautista/miniconda2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

Thanks!

Maria

**Comment by nlapier2** [comment]
I am still unable to replicate this error. I've read that this can pop up if the file is not executable. Can you try checking the permissions of MiCoP/bwa.kit/bwa and making sure that you can execute the file?

(If you don't know how to do this, let me know what the output of "ls -lh MiCoP/bwa.kit/bwa" is.)

**Comment by nlapier2** [comment]
I've also pushed some changes that make the scripts compatible with both python 2 and python 3, and changed the subprocess execution call format in a way that may address the issue, so it's worth trying again. However, I suspect that this may be a permissions issue. Let me know what you find.

Best,
Nathan
